### ISSUE TITLE
invalid indirect of hit.Source (type json.RawMessage)

### ISSUE THREAD

**Issue by suhyunjeon** [olivere/esdiff#3]
- go version
```
go version go1.12.6 linux/amd64
```

- errors
```
$  go install github.com/olivere/esdiff
# github.com/olivere/esdiff/elastic/v6
../go/esdiff/src/github.com/olivere/esdiff/elastic/v6/client.go:137:27: invalid indirect of hit.Source (type json.RawMessage)
```

**Comment by olivere** [comment]
Not sure what that is. Do you have Go modules enabled?

**Comment by michael-todorovic** [comment]
Hello, I have the same issue on Debian Buster with go 1.11 (quite fresh & default installation)

**Comment by olivere** [comment]
@michael-todorovic Do you have Go modules enabled?

**Comment by olivere** [comment]
`Invalid indirect of hit.Source (type json.RawMessage)` looks like you're using v7, not v6. And that could be due to you using the v7 branch of `github.com/olivere/elastic`, not the v6 branch.

**Comment by michael-todorovic** [comment]
> @michael-todorovic Do you have Go modules enabled?

As per https://github.com/golang/go/wiki/Modules#quick-start, I'm using go 1.11 so Go modules are not enabled by default

**Comment by olivere** [comment]
With elastic v7, you need to enable modules.

**Comment by olivere** [comment]
With v0.2.0, you need to use Go modules because elastic v7.x is Go modules only.

**Comment by Arpit1596** [comment]
I am also having the same issue but I am using go modules

**Comment by olivere** [comment]
@Arpit1596 You mix v6 with v7, somehow. Because that was a breaking change from v6 to v7. If you want me to help, please provide a reproducible test case.

**Comment by Arpit1596** [comment]
import "github.com/olivere/elastic/v7"

if err := json.Unmarshal(*hit.Source, &r); err != nil {
			log.Errorf("ERROR UNMARSHALLING ES SUGGESTION RESPONSE: %v", err)
			continue
		}


this is my go.mod file

require (
	github.com/micro/go-micro v1.14.0
	github.com/micro/go-plugins v1.4.0
	github.com/olivere/elastic/v7 v7.0.9
	github.com/prometheus/common v0.6.0
	github.com/stretchr/testify v1.4.0
	golang.org/x/net v0.0.0-20191011234655-491137f69257
	google.golang.org/grpc v1.24.0
)

**Comment by olivere** [comment]
Try:

```
if err := json.Unmarshal(hit.Source, &r); err != nil {
  log.Errorf("ERROR UNMARSHALLING ES SUGGESTION RESPONSE: %v", err)
  continue
}
```

**Comment by Arpit1596** [comment]
@olivere got the issue .. thanks.

**Comment by davidelena** [comment]
> Try:
> 
> ```
> if err := json.Unmarshal(hit.Source, &r); err != nil {
>   log.Errorf("ERROR UNMARSHALLING ES SUGGESTION RESPONSE: %v", err)
>   continue
> }
> ```

I met the same issue and this comment is very useful.
